export const Head = () => {
   return (
      <>
         <title>Portfolio</title>
         <meta content="width=device-width, initial-scale=1" name="viewport" />
         <meta name="description" content="Generated by create next app" />
         <link
            rel="icon"
            type="image/png"
            href="https://img.icons8.com/neon/96/null/dinosaur.png"
         />
      </>
   );
};
